export const businessTypeValues = [
    "Venda",
    "Arrendamento",
    "Transpasse",
]

export const immobileTypeValues = [
    "Apartamento",
    "Casa",
    "Comercial",
    "Terreno",
    "Áreas",
]
export const countyValues = [
    "Abrantes",
    "Agualva-Cacém",
    "Albergaria-a-Velha",
    "Alenquer",
    "Alvaiázere",
    "Amarante",
    "Arouca",
    "Estremoz",
    "Faro",
    "Gaia",
    "Gondomar",
    "Horta",
    "Lousada",
    "Maia",
    "Marco de Canaveses",
    "Matosinhos",
    "Montijo",
    "Olhão",
    "Oliveira de Azemeis",
    "Ovar",
    "Paços de Ferreira",
    "Paredes",
    "Penafiel",
    "Ponte da Barca",
    "Porto",
    "Povoa de Varzim",
    "Santo Tirso",
    "Setubal",
    "Sintra",
    "Tabuaço",
    "Tondela",
    "Valongo",
    "Vila do Conde",
    "Vila Franca de xira",
    "Vila Nova de Famalicão",
    "Vila Nova de Gala",
    "Vila Verde",
    "Viseu",
]

export const districtValues = [
    "Aveiro",
    "Braga",
    "Evora",
    "Faro",
    "Horta",
    "Leiria",
    "Lisboa",
    "Porto",
    "Santarem",
    "Setúbal",
    "Viana do Castelo",
    "Viseu",
]